-- ================================================================
-- Indexes used for access, reconciliation and reporting.
-- ================================================================

CREATE UNIQUE INDEX IX_FIN_ACCOUNT_NUMBER
    ON FIN_ACCOUNT (ACCOUNT_NUMBER);

CREATE UNIQUE INDEX IX_FIN_MOVEMENT_TRANS
    ON FIN_MOVEMENT (TRANSACTION_ID);

CREATE INDEX IX_FIN_MOVEMENT_ACC_DATE
    ON FIN_MOVEMENT (ACCOUNT_ID, MOVEMENT_DATE);

CREATE UNIQUE INDEX IX_FIN_STG_TRANS
    ON FIN_STG_MOVEMENT (TRANSACTION_ID);

CREATE INDEX IX_FIN_STG_STATUS_DATE
    ON FIN_STG_MOVEMENT (PROCESS_STATUS, TRANSACTION_DATE);

CREATE INDEX IX_FIN_RECON_ACCOUNT_STATUS
    ON FIN_RECON_CONTROL (ACCOUNT_NUMBER, STATUS);

CREATE INDEX IX_FIN_DISC_TRANS_ERROR
    ON FIN_DISCREPANCY (TRANSACTION_ID, ERROR_CODE);

CREATE INDEX IX_FIN_AUDIT_PROCESS_TS
    ON FIN_AUDIT_LOG (PROCESS_NAME, EVENT_TIMESTAMP);
