-- ================================================================
-- Sample data used for local testing.
-- ================================================================

INSERT INTO FIN_ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_HOLDER, ACCOUNT_STATUS, CURRENCY, OPEN_DATE)
VALUES ('1000000001', 'JANE DOE', 'A', 'EUR', DATE '2020-01-15');

INSERT INTO FIN_ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_HOLDER, ACCOUNT_STATUS, CURRENCY, OPEN_DATE)
VALUES ('1000000002', 'JOHN SMITH', 'A', 'EUR', DATE '2021-06-20');

INSERT INTO FIN_ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_HOLDER, ACCOUNT_STATUS, CURRENCY, OPEN_DATE)
VALUES ('1000000003', 'BLOCKED ACCOUNT', 'B', 'EUR', DATE '2022-05-10');

INSERT INTO FIN_MOVEMENT
    (TRANSACTION_ID, ACCOUNT_ID, MOVEMENT_DATE, MOVEMENT_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, SOURCE_SYSTEM)
VALUES
    ('TXN0001', 1, DATE '2026-05-01', 'CR', 150.00, 'EUR', 'PAYROLL-APR', 'BATCH', 'CORE_BANK');

INSERT INTO FIN_MOVEMENT
    (TRANSACTION_ID, ACCOUNT_ID, MOVEMENT_DATE, MOVEMENT_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, SOURCE_SYSTEM)
VALUES
    ('TXN0002', 2, DATE '2026-05-02', 'DB', 250.00, 'EUR', 'UTILITY-BILL', 'BATCH', 'CORE_BANK');

INSERT INTO FIN_STG_MOVEMENT
    (TRANSACTION_ID, TRANSACTION_DATE, ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, PROCESS_STATUS)
VALUES
    ('TXN0001', DATE '2026-05-01', '1000000001', 'CR', 150.00, 'EUR', 'PAYROLL-APR', 'BATCH', 'N');

INSERT INTO FIN_STG_MOVEMENT
    (TRANSACTION_ID, TRANSACTION_DATE, ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, PROCESS_STATUS)
VALUES
    ('TXN0002', DATE '2026-05-02', '1000000002', 'DB', 255.00, 'EUR', 'UTILITY-BILL', 'BATCH', 'N');

INSERT INTO FIN_STG_MOVEMENT
    (TRANSACTION_ID, TRANSACTION_DATE, ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, PROCESS_STATUS)
VALUES
    ('TXN0003', DATE '2026-05-03', '9999999999', 'CR', 100.00, 'EUR', 'UNKNOWN-REF', 'BATCH', 'N');

INSERT INTO FIN_STG_MOVEMENT
    (TRANSACTION_ID, TRANSACTION_DATE, ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, CURRENCY, REFERENCE, CHANNEL, PROCESS_STATUS)
VALUES
    ('TXN0004', DATE '2026-05-04', '1000000003', 'CR', 80.00, 'EUR', 'BLOCKED-ACC', 'BATCH', 'N');
